### ISSUE TITLE
Next.js hydration errors

### ISSUE THREAD

**Issue by kartomek** [TylerAHolden/react-schedule-meeting#73]
The locale prop has not been passed to react-calendar, causing hydration errors when using Next.js

**Comment by TylerAHolden** [comment]
The locale prop is actually the Locale type for the date-fns library. Although there is a locale prop for react-calendar, it's not exposed. If you want to pass in a locale prop for the react-calendar we would need to expose a different locale prop type which can be done if that's really what you need but I'm curious what you are seeing to believe this is causing hydration errors? I used to have this component on a nextJS 12 site without issue - are you seeing issues on the app router project type?

**Comment by dr-aiuta** [comment]
My project used version 0.3.3 with React 16. After upgrading to React 18 and the last version, I'm getting the same errors.

1. Unhandled Runtime Error
Error: Text content does not match server-rendered HTML.
2. Unhandled Runtime Error
Error: Hydration failed because the initial UI does not match what was rendered on the server.
3. Unhandled Runtime Error
Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
