### ISSUE TITLE
Confirmed Time Slot

### ISSUE THREAD

**Issue by OmarBaltaji** [TylerAHolden/react-schedule-meeting#9]
Hello I was just wondering, how can I disable clicking on (or hide)  a certain time slot if it has been already booked? I understand I need to use the splitTimeslot option but I am unsure of how to pass it again to the Schedule Meeting component.
Thank you in advance!

**Comment by TylerAHolden** [comment]
Hi Omar, anytime the availableTimeslot prop changes, the component will re-calculate the available timeslots. So if you wanted to remove a timeslot you could remove that time from the array of available timeslots. The onStartTimeSelect callback will pass back the splitTimeslot so that you could replace the original available timeslot with the two new ones. Does that make sense or are you asking for something else?
